# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-10 05:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shelf', '0003_auto_20170810_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(default=datetime.datetime(2017, 8, 10, 5, 47, 22, 863277, tzinfo=utc))),
                ('returned', models.DateTimeField(blank=True, null=True)),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.BookItem')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
