# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-10 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_auto_20170803_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BootItem',
            new_name='BookItem',
        ),
        migrations.AlterField(
            model_name='bookedition',
            name='isbn',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
