# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20170810_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='catalogue_number',
        ),
    ]
