# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_remove_bookitem_catalogue_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='cover_type',
        ),
        migrations.AddField(
            model_name='bookitem',
            name='catalogue_numb',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
