# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_auto_20170816_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='cover_type',
            field=models.CharField(choices=[('soft', 'Soft'), ('hard', 'Hard')], default='Soft', max_length=4),
        ),
    ]
